### ISSUE TITLE
pseudoT is Inf for small pvalues

### ISSUE THREAD

**Issue by julianesiebourg** [bedapub/ribiosNGS#6]
For very small p-values the pseudoT is Inf. We've been using a p-value threshold in the past to prevent this.
What one could do would be something along those lines:

```
pseudoTfromPvalue <- function(p, df, sign) {
  if (is.logical(sign))
    sign <- ifelse(sign, 1, -1)
  if (p < 10E-300) {# asymtote value for extremely small p values
    p <- 10E-300
    message('P value below threshold has been replaced with 10E-300')
  }
 stats::qt(p=1-p/2, df=df) * sign(sign)
}
```

Sorry for not making a pull request... I'm getting there slowly ;)

**Comment by Accio** [comment]
thanks @julianesiebourg! It was fixed in 93e13b3 (though using a slightly different implementation, which was done already in ribiosUtils). In case of doubt please re-open it or do the PR:)
